- name: Ping my hosts
  ansible.builtin.ping:

- name: Print message
  ansible.builtin.debug:
    msg: Hello world

- name: Copy myscript.sh to the server
  ansible.builtin.copy:
    src: roles/common/files/myscript.sh
    dest: /tmp/myscript.sh
    mode: '0755'
    owner: root
    group: root